/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as CandidatesRouteImport } from './routes/candidates'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JobsIndexRouteImport } from './routes/jobs.index'
import { Route as JobsNewRouteImport } from './routes/jobs.new'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'
import { Route as InterviewsInterviewIdRouteImport } from './routes/interviews.$interviewId'
import { Route as CandidatesCandidateIdRouteImport } from './routes/candidates.$candidateId'
import { Route as ApplyJobIdRouteImport } from './routes/apply.$jobId'
import { Route as JobsJobIdIndexRouteImport } from './routes/jobs.$jobId.index'
import { Route as JobsJobIdRankingRouteImport } from './routes/jobs.$jobId.ranking'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesRoute = CandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JobsRoute,
} as any)
const JobsNewRoute = JobsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => JobsRoute,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => JobsRoute,
} as any)
const InterviewsInterviewIdRoute = InterviewsInterviewIdRouteImport.update({
  id: '/interviews/$interviewId',
  path: '/interviews/$interviewId',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesCandidateIdRoute = CandidatesCandidateIdRouteImport.update({
  id: '/$candidateId',
  path: '/$candidateId',
  getParentRoute: () => CandidatesRoute,
} as any)
const ApplyJobIdRoute = ApplyJobIdRouteImport.update({
  id: '/apply/$jobId',
  path: '/apply/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdIndexRoute = JobsJobIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JobsJobIdRoute,
} as any)
const JobsJobIdRankingRoute = JobsJobIdRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => JobsJobIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/candidates': typeof CandidatesRouteWithChildren
  '/jobs': typeof JobsRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/apply/$jobId': typeof ApplyJobIdRoute
  '/candidates/$candidateId': typeof CandidatesCandidateIdRoute
  '/interviews/$interviewId': typeof InterviewsInterviewIdRoute
  '/jobs/$jobId': typeof JobsJobIdRouteWithChildren
  '/jobs/new': typeof JobsNewRoute
  '/jobs/': typeof JobsIndexRoute
  '/jobs/$jobId/ranking': typeof JobsJobIdRankingRoute
  '/jobs/$jobId/': typeof JobsJobIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/candidates': typeof CandidatesRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/apply/$jobId': typeof ApplyJobIdRoute
  '/candidates/$candidateId': typeof CandidatesCandidateIdRoute
  '/interviews/$interviewId': typeof InterviewsInterviewIdRoute
  '/jobs/new': typeof JobsNewRoute
  '/jobs': typeof JobsIndexRoute
  '/jobs/$jobId/ranking': typeof JobsJobIdRankingRoute
  '/jobs/$jobId': typeof JobsJobIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/candidates': typeof CandidatesRouteWithChildren
  '/jobs': typeof JobsRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/apply/$jobId': typeof ApplyJobIdRoute
  '/candidates/$candidateId': typeof CandidatesCandidateIdRoute
  '/interviews/$interviewId': typeof InterviewsInterviewIdRoute
  '/jobs/$jobId': typeof JobsJobIdRouteWithChildren
  '/jobs/new': typeof JobsNewRoute
  '/jobs/': typeof JobsIndexRoute
  '/jobs/$jobId/ranking': typeof JobsJobIdRankingRoute
  '/jobs/$jobId/': typeof JobsJobIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/applications'
    | '/candidates'
    | '/jobs'
    | '/login'
    | '/profile'
    | '/signup'
    | '/apply/$jobId'
    | '/candidates/$candidateId'
    | '/interviews/$interviewId'
    | '/jobs/$jobId'
    | '/jobs/new'
    | '/jobs/'
    | '/jobs/$jobId/ranking'
    | '/jobs/$jobId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/applications'
    | '/candidates'
    | '/login'
    | '/profile'
    | '/signup'
    | '/apply/$jobId'
    | '/candidates/$candidateId'
    | '/interviews/$interviewId'
    | '/jobs/new'
    | '/jobs'
    | '/jobs/$jobId/ranking'
    | '/jobs/$jobId'
  id:
    | '__root__'
    | '/'
    | '/applications'
    | '/candidates'
    | '/jobs'
    | '/login'
    | '/profile'
    | '/signup'
    | '/apply/$jobId'
    | '/candidates/$candidateId'
    | '/interviews/$interviewId'
    | '/jobs/$jobId'
    | '/jobs/new'
    | '/jobs/'
    | '/jobs/$jobId/ranking'
    | '/jobs/$jobId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplicationsRoute: typeof ApplicationsRoute
  CandidatesRoute: typeof CandidatesRouteWithChildren
  JobsRoute: typeof JobsRouteWithChildren
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  SignupRoute: typeof SignupRoute
  ApplyJobIdRoute: typeof ApplyJobIdRoute
  InterviewsInterviewIdRoute: typeof InterviewsInterviewIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidates': {
      id: '/candidates'
      path: '/candidates'
      fullPath: '/candidates'
      preLoaderRoute: typeof CandidatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof JobsRoute
    }
    '/jobs/new': {
      id: '/jobs/new'
      path: '/new'
      fullPath: '/jobs/new'
      preLoaderRoute: typeof JobsNewRouteImport
      parentRoute: typeof JobsRoute
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof JobsRoute
    }
    '/interviews/$interviewId': {
      id: '/interviews/$interviewId'
      path: '/interviews/$interviewId'
      fullPath: '/interviews/$interviewId'
      preLoaderRoute: typeof InterviewsInterviewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidates/$candidateId': {
      id: '/candidates/$candidateId'
      path: '/$candidateId'
      fullPath: '/candidates/$candidateId'
      preLoaderRoute: typeof CandidatesCandidateIdRouteImport
      parentRoute: typeof CandidatesRoute
    }
    '/apply/$jobId': {
      id: '/apply/$jobId'
      path: '/apply/$jobId'
      fullPath: '/apply/$jobId'
      preLoaderRoute: typeof ApplyJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId/': {
      id: '/jobs/$jobId/'
      path: '/'
      fullPath: '/jobs/$jobId/'
      preLoaderRoute: typeof JobsJobIdIndexRouteImport
      parentRoute: typeof JobsJobIdRoute
    }
    '/jobs/$jobId/ranking': {
      id: '/jobs/$jobId/ranking'
      path: '/ranking'
      fullPath: '/jobs/$jobId/ranking'
      preLoaderRoute: typeof JobsJobIdRankingRouteImport
      parentRoute: typeof JobsJobIdRoute
    }
  }
}

interface CandidatesRouteChildren {
  CandidatesCandidateIdRoute: typeof CandidatesCandidateIdRoute
}

const CandidatesRouteChildren: CandidatesRouteChildren = {
  CandidatesCandidateIdRoute: CandidatesCandidateIdRoute,
}

const CandidatesRouteWithChildren = CandidatesRoute._addFileChildren(
  CandidatesRouteChildren,
)

interface JobsJobIdRouteChildren {
  JobsJobIdRankingRoute: typeof JobsJobIdRankingRoute
  JobsJobIdIndexRoute: typeof JobsJobIdIndexRoute
}

const JobsJobIdRouteChildren: JobsJobIdRouteChildren = {
  JobsJobIdRankingRoute: JobsJobIdRankingRoute,
  JobsJobIdIndexRoute: JobsJobIdIndexRoute,
}

const JobsJobIdRouteWithChildren = JobsJobIdRoute._addFileChildren(
  JobsJobIdRouteChildren,
)

interface JobsRouteChildren {
  JobsJobIdRoute: typeof JobsJobIdRouteWithChildren
  JobsNewRoute: typeof JobsNewRoute
  JobsIndexRoute: typeof JobsIndexRoute
}

const JobsRouteChildren: JobsRouteChildren = {
  JobsJobIdRoute: JobsJobIdRouteWithChildren,
  JobsNewRoute: JobsNewRoute,
  JobsIndexRoute: JobsIndexRoute,
}

const JobsRouteWithChildren = JobsRoute._addFileChildren(JobsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplicationsRoute: ApplicationsRoute,
  CandidatesRoute: CandidatesRouteWithChildren,
  JobsRoute: JobsRouteWithChildren,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  SignupRoute: SignupRoute,
  ApplyJobIdRoute: ApplyJobIdRoute,
  InterviewsInterviewIdRoute: InterviewsInterviewIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
